version: "3.8"

volumes:
  db_data:

services:
  database:
    image: postgres:latest
    container_name: postgres-authentication-on-rails
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456789
      POSTGRES_DB: authentication
    volumes:
      - db_data:/var/lib/postgresql/data
      - type: tmpfs
        target: /dev/shm
    restart: "no"
  app:
    build:
      context: .
    image: authentication-on-rails:latest
    ports:
      - "3000:3000"
    environment:
      - USER=wesleyricardi
      - POSTGRES_URL=postgres://postgres:123456789@database:5432
      - DATABASE_URL=postgres://postgres:123456789@database:5432/authentication
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - database
